### ISSUE TITLE
Not working for 4.1?

### ISSUE THREAD

**Issue by GeorgeS2019** [athillion/ProceduralPlanetGodot#1]

**Comment by henriksod** [comment]
Hi, I haven't had time to test this for 4.1 yet. I made this project in the Godot 4 beta. Please specify what is causing issues for you!

**Comment by GeorgeS2019** [comment]
I tried Godot_v4.0-beta2_win64, it works but atmosphere fails [here](https://github.com/athillion/ProceduralPlanetGodot/blob/2cdaa153053d64ee564c359860ebc5f0213dce80/scripts/planet/settings/AtmosphereSettings.gd#L162)

=> Stated in youtube to try beta5

**Comment by GeorgeS2019** [comment]
@henriksod 
Recommended this for Official [Godot4 **Compute Shader** demo](https://github.com/godotengine/godot-demo-projects/pull/938#issuecomment-1656733395)

**Comment by henriksod** [comment]
I will look into this soon, just need to finish off some other projects first 😅

**Comment by GeorgeS2019** [comment]
@henriksod 
[Updated to 4.1](https://github.com/athillion/ProceduralPlanetGodot/pull/2#issuecomment-1684493812) :-)
